image: python:alpine

stages:
  - deploy

before_script:
  - pip install twine

variables:
  TWINE_USERNAME: SECURE
  TWINE_PASSWORD: SECURE

deploy:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
  except:
    - branches